require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/MultipleMemoizedHelpers:
  Max: 12

Style/Documentation:
  Exclude:
    - 'config/*.rb'
    - 'db/migrate/*.rb'
