# frozen_string_literal: true

Dotenv.require_keys(
  'GITHUB_API_TOKEN',
  'GITHUB_USERNAME',
  'RAILS_MASTER_KEY',
  'SENTRY_DSN',
  'SIDEKIQ_PASSWORD',
  'SIDEKIQ_USERNAME',
  'TICKETMASTER_API_KEY',
  'TWILIO_PHONE_NUMBER',
  'TWILIO_ACCOUNT_SID',
  'TWILIO_AUTH_TOKEN',
  'TWILIO_MESSAGING_SERVICE_SID'
)
