development:
  :concurrency: 5
production:
  :concurrency: 10
:queues:
  - <%= ENV.fetch('RAILS_ENV', 'development') %>_high
  - <%= ENV.fetch('RAILS_ENV', 'development') %>_default
  - <%= ENV.fetch('RAILS_ENV', 'development') %>_mailers
